### PR TITLE
[release] add torch button for nightly build

### PR DESCRIPTION
**Pull request by Rhett-Ying**
Screenshot 2024-04-15 at 11 43 57

### CODE REVIEW

**Comment by Rhett-Ying** [comment]
Don't merge it right now. I will merge it when nightly build is ready

**Comment by frozenbugs** [comment]
What does it look like if the selected PyTorch version does not match with CUDA?

**Review by frozenbugs — APPROVED** [review]

**Comment by Rhett-Ying** [comment]
image

**Comment by frozenbugs** [comment]
LGTM

**Comment by Rhett-Ying** [comment]
At least one nightly build is ready for now, it's ok to merge it.

**Comment by Rhett-Ying** [comment]
wheel package size comparison: **741.8MB -> 491.3MB**
1. Before torch split which includes torch **2.1.0/1/2, 2.2.0/1, 5** torch versions in total.
https://data.dgl.ai/wheels-test/cu121/dgl-2.2a240410+cu121-cp39-cp39-manylinux1_x86_64.whl
741.8MB
2. After torch split which includes torch **2.1.0/1/2, 3** torch versions in total for torch 2.1.x
https://data.dgl.ai/wheels-test/torch-2.1/cu121/dgl-2.2a240412+cu121-cp310-cp310-manylinux1_x86_64.whl
491.3MB

**Pull request merged**
