### PR TITLE
[Blog] Fix gat blog

### PR DESCRIPTION
**Pull request by mufeili**
This PR serves the same purpose as [[Tutorial] Hotfix for GAT Tutorial](https://github.com/dmlc/dgl/pull/420). 

## Changes
- [x] Removed the sentence describing the entropy distribution for the final GAT layer on PPI.
- [x] Replaced all the entropy histogram plots for PPI.

I'm not sure why github recognizes so many lines of change while I've only changed very few lines @jermainewang .

### CODE REVIEW

**Comment by jermainewang** [comment]
This is unfortunate. Ideally, we only need to host jekyll files and github will generate these static pages for us. However, one of our jekyll plugins is not supported so we end up with putting all the generated files on github as well. Thus, in the change log you will find a lot of changes in the generated HTML but you only need to pay attention to the changes under jekyll folder. Also, when merging the code, you could just ignore the conflicts in the generated HTML.

**Comment by mufeili** [comment]
@jermainewang Done.

**Comment by jermainewang** [comment]
I merged another PR and resulted in some conflicts here. You could simply discard your changes in those generated files.

**Comment by mufeili** [comment]
@jermainewang Done.

**Pull request merged**
